name: Branch Sanitization Demo

on:
  workflow_dispatch:

jobs:
  demo:
    runs-on: ubuntu-latest
    steps:
      - name: Vulnerable Branch Name Handling
        run: |
          echo "Simulating malicious branch name with newline injection..."
          BRANCH="feature/hotfix
          MALICIOUS_VAR=HACKED"
          echo "TAG=${BRANCH//[^A-Za-z0-9:]/-}" >> $GITHUB_ENV

      - name: Print Environment Variables (Vulnerable)
        run: |
          echo "TAG=$TAG"
          echo "MALICIOUS_VAR=$MALICIOUS_VAR"

      - name: Safe Branch Name Handling
        run: |
          echo "Sanitizing branch name safely..."
          BRANCH="feature/hotfix
          MALICIOUS_VAR=HACKED"
          SAFE_BRANCH=$(echo "$BRANCH" | tr -d '\n\r' | tr -c 'A-Za-z0-9:-' '-' | tr -s '-' | sed 's/-$//')
          echo "TAG_SAFE=$SAFE_BRANCH" >> $GITHUB_ENV

      - name: Print Environment Variables (Safe)
        run: |
          echo "TAG_SAFE=$TAG_SAFE"
          echo "MALICIOUS_VAR=$MALICIOUS_VAR"
